# SPDX-License-Identifier: Apache-2.0

name: E2E test

on:
  # REMOVE THE PULL REQUEST TRIGGER BEFORE MERGING
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      pr_or_branch:
        description: 'pull request number or branch name'
        required: true
        default: 'main'

jobs:
  e2e:
    runs-on: ubuntu-gpu

    steps:
      - name: Setup
        run: |
          sudo apt-get install -y cuda-toolkit python3 git python3-pip cmake build-essential
          nvidia-smi
          ls -l /dev/nvidia*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # https://github.com/actions/checkout/issues/249
          fetch-depth: 0
          submodules: 'true'

      - name: Determine if pr_or_branch is a PR number
        id: check_pr
        run: |
          if [[ "${{ github.event.inputs.pr_or_branch }}" =~ ^[0-9]+$ ]]; then
            echo "is_pr=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_pr=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fetch and checkout PR
        if: steps.check_pr.outputs.is_pr == 'true'
        run: |
          git fetch origin pull/${{ github.event.inputs.pr_or_branch }}/head:pr-${{ github.event.inputs.pr_or_branch }}
          git checkout pr-${{ github.event.inputs.pr_or_branch }}

      - name: Checkout branch
        if: steps.check_pr.outputs.is_pr == 'false'
        run: git checkout ${{ github.event.inputs.pr_or_branch }}

      - name: Install dependencies
        run: |
          export PATH="/home/runner/.local/bin:/usr/local/cuda-12.4/bin:$PATH"
          CMAKE_ARGS="-DLLAMA_CUBLAS=on" python3 -m pip install -r requirements.txt --force-reinstall --no-cache-dir llama-cpp-python
          python3 -m pip install .
          ./scripts/basic-workflow-tests.sh
